/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTickets"];
        put?: never;
        post: operations["CreateTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UpdateTicket"];
        post?: never;
        delete: operations["DeleteTicket"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TicketStatus: TicketStatus;
        /** @enum {string} */
        TicketPriority: TicketPriority;
        Customer: {
            name: string;
            /** Format: email */
            email: string;
            /** @description Numer telefonu w formacie międzynarodowym (np. +48123456789) */
            phone: string;
        };
        Ticket: {
            /** Format: double */
            id: number;
            title: string;
            description: string;
            status: components["schemas"]["TicketStatus"];
            priority: components["schemas"]["TicketPriority"];
            createdAt: string;
            updatedAt: string;
            assignedTo: string;
            customer: components["schemas"]["Customer"];
        };
        /** @description From T, pick a set of properties whose keys are in the union K */
        "Pick_Ticket.Exclude_keyofTicket.id-or-createdAt-or-updatedAt__": {
            title: string;
            description: string;
            status: components["schemas"]["TicketStatus"];
            priority: components["schemas"]["TicketPriority"];
            assignedTo: string;
            customer: components["schemas"]["Customer"];
        };
        /** @description Construct a type with the properties of T except for those in type K. */
        "Omit_Ticket.id-or-createdAt-or-updatedAt_": components["schemas"]["Pick_Ticket.Exclude_keyofTicket.id-or-createdAt-or-updatedAt__"];
        TicketCreationParams: components["schemas"]["Omit_Ticket.id-or-createdAt-or-updatedAt_"];
        /** @description Make all properties in T optional */
        "Partial_Omit_Ticket.id-or-createdAt-or-updatedAt__": {
            title?: string;
            description?: string;
            status?: components["schemas"]["TicketStatus"];
            priority?: components["schemas"]["TicketPriority"];
            assignedTo?: string;
            customer?: components["schemas"]["Customer"];
        };
        TicketUpdateParams: components["schemas"]["Partial_Omit_Ticket.id-or-createdAt-or-updatedAt__"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetTickets: {
        parameters: {
            query?: {
                status?: components["schemas"]["TicketStatus"];
                search?: string;
                assignedTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"][];
                };
            };
        };
    };
    CreateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreationParams"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
        };
    };
    UpdateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketUpdateParams"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"] | null;
                };
            };
        };
    };
    DeleteTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
export enum TicketStatus {
    new = "new",
    open = "open",
    closed = "closed",
    pending = "pending",
    on_hold = "on_hold",
    cancelled = "cancelled"
}
export enum TicketPriority {
    low = "low",
    medium = "medium",
    high = "high"
}
